// <auto-generated />
namespace PContactDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class SeagregalaentidaddeTipoContacto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SeagregalaentidaddeTipoContacto));
        
        string IMigrationMetadata.Id
        {
            get { return "201809110323472_Se agrega la entidad de TipoContacto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
